### ISSUE TITLE
MCS and MI

### ISSUE THREAD

**Issue by yograjyog** [victorgabr/ApertureComplexity#1]
Hello Victor! Is there any possibility to calculate other metrics like MCS, MI with this script? I really appreciate your help. Many Thanks.

**Comment by victorgabr** [comment]
The list of implemented metrics is located at:

https://github.com/victorgabr/ApertureComplexity/blob/master/complexity/PyComplexityMetric.py

I am not sure what you mean by MCS, but there are many on the file above.

**Comment by yograjyog** [comment]
Thanks. Can u plz give a sample code on how to calculate MeanApertureAreaMetric. Appreciate your help. 


I have  tried this

`from complexity.PyComplexityMetric import MeanApertureAreaMetric
from complexity.dicomrt import RTPlan

if __name__ == '__main__':
    
pfile ='E:\\MedPhy\\Medical Physics Library\\Research\\Aperture Shape Controller Evaluation\\High.dcm'
    plan_info = RTPlan(filename=pfile)
    plan_dict = plan_info.get_plan()
    beams = [beam for k, beam in plan_dict['beams'].items()]
    complexity_obj = MeanApertureAreaMetric()
    mean_aperture_area = complexity_obj.Calculate`????

I am stuck.

**Comment by victorgabr** [comment]
I have added more examples.
Other metrics inherited from PyComplexityMetric. So the API for usage is the same.
Check the README.md.

There are also more complex metrics on the file: 
[https://github.com/victorgabr/ApertureComplexity/blob/master/complexity/misc.py](https://github.com/victorgabr/ApertureComplexity/blob/master/complexity/misc.py)

Including MCS.

**Comment by yograjyog** [comment]
Thanks a lot
